### ISSUE TITLE
オーディオファイル出力が途中から進まなくなってしまうことがある

### ISSUE THREAD

**Issue by grj1234** [argentum384/flmml-on-html5#56]
レンダリング時の負荷が大きいMMLをオーディオファイルとして出力しようとすると、出力処理が途中から進まなくなる現象が発生することを確認しました。  
当方の環境では、[mml/21290](https://dic.nicovideo.jp/mml/21290)や[mml/21291](https://dic.nicovideo.jp/mml/21291)などで当該現象の発生を確認しました。  
なお、処理が進まなくなった状態で`flmml.stop()`を実行した場合は、処理が進まなくなるまでの分のオーディオファイルが出力されます。  
この現象の発生原因の調査、および不具合修正をお願いしたく思います。  
お手数をおかけしますが、何卒よろしくお願いいたします。

**Comment by argentum384** [comment]
手持ちの環境の中では例示のMML[2つ目](https://dic.nicovideo.jp/mml/21291) かつ Firefox for Android でのみ100% (n=10以上) 再現を確認。他ブラウザや他MMLの組み合わせでは再現確認できず。

調査したところオーディオファイル出力に限った話ではなさそうなので #57 に調査結果とともに起票

**Comment by argentum384** [comment]
v2.0.3 で修正リリース済

**Comment by grj1234** [comment]
ありがとうございましたm(_ _)m
